version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.0
executors:
  chrome-firefox:
    docker:
      - image: "cypress/browsers:node12.18.3-chrome87-ff82"
workflows:
  build:
    jobs:
      - cypress/install:
          executor: chrome-firefox
      - cypress/run:
          executor: chrome-firefox
          requires:
            - cypress/install
          attach-workspace: true
          record: false
          matrix:
            parameters:
              browser: [chrome, firefox, electron]
